import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({ subsets: ['latin'], weight: ["300" , "700"] })
const openSans = Open_Sans({ subsets: ['latin'], weight: ["300" , "700","400" , "500", "600"] })


export const metadata: Metadata = {
  title: "Arbisoft Tax Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
