import type { Metadata } from "next";
import { Inter, Roboto, Lato, Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ['latin'], weight: ["300" , "700"] })
const lato = Open_Sans({ subsets: ['latin'], weight: ["300" , "700","400" , "500", "600"] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
